//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAD_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterTBL
    {//
        public int Id { get; set; }
        public string CharacterName { get; set; }
        public string ActorName { get; set; }
        public string HouseName { get; set; }
    }
}
